title: Spider Blog
author: Corbett
email: corbettbw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is full of spiders

# social links
twitter_username: @corbettbw
github_username:  @corbettbw

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
